### PR TITLE
Add a copy short hash helper

### PR DESCRIPTION
**Pull request by Benuuu**
I also have it aliased with: `alias gsha='git log -n 1 --oneline | awk "{print \$1}" | tr -d \\n | pbcopy'`

### CODE REVIEW

**Comment by gdaniels** [comment]
:+1:

**Comment by loganwright** [comment]
:ship:

**Comment by gdaniels** [comment]
Rebase and ship?

**Comment by Benuuu** [comment]
oops yeah. forgot about this guy.

**Pull request merged**
