### PR TITLE
Update Jenkins README for SonarQube PR Lint Reporting

### PR DESCRIPTION
**Pull request by deanshi**

### CODE REVIEW

**Review by mpeng3 — APPROVED** [review]
Looks good to me, but FYI I haven't run any of this since I'm not familiar with the Bose/SonarQube build process - but based on content here this looks fine. ;-)

**Comment by deanshi** [comment]
It should work for any PR builder we have on Jenkins, not just Bose. I might set this up on a different PR builder (non-Bose) for a project just to make sure the instructions are okay before merging, as long as no one is angry that the PR remains up :)

**Comment by gdaniels** [comment]
Hey @deanshi do we have everything we need to merge this yet, or still have testing to do?

**Comment by deanshi** [comment]
I believe this is good to merge, although I thought I ran into a hiccup when trying to implement it on a repo. I'll double check my steps but for now I think I'll merge.

**Pull request merged**
